blog/urls.py
from django.urls import path

from blog.apps import BlogConfig

from blog.views import BlogCreate, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreate.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.views import contacts_page, ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, categories

from catalog.apps import CatalogConfig

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('contacts/', contacts_page, name='contacts'),
    path('product/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('create/', ProductCreateView.as_view(), name='create_product'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),
    path('categories/', categories, name='categories'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}

class Blog(models.Model):
   title = models.CharField(max_length=150, verbose_name='заголовок')
   slug = models.CharField(max_length=100, verbose_name='slug', **NULLABLE)
   content = models.TextField(verbose_name='содержание', **NULLABLE)
   preview = models.ImageField(upload_to='blog/', verbose_name='изображение', **NULLABLE)
   date_of_creation = models.DateField(auto_now_add=True, verbose_name='дата создания')
   is_published = models.BooleanField(default=True, verbose_name='опубликовано')
   views_count = models.IntegerField(default=0, verbose_name='просмотры')

   def __str__(self):
       return self.title

   class Meta:
       verbose_name  = 'материал'
       verbose_name_plural = 'материалы'

blog/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from pytils.translit import slugify

from blog.models import Blog


class BlogCreate(CreateView):
    model = Blog
    fields = ('title', 'content',)
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)

class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset




class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count +=1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'content',)

    def get_success_url(self):
        return reverse('blog:view', kwargs={'pk': self.kwargs.get('pk')})

class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')

blog/templates/blog/base_blog.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>BlogSpot</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-black border-bottom box-shadow">
    <h4 class="my-0 mr-md-auto font-weight-normal rounded-pill text-white p-2">BlogSpot</h4>
    <nav class="ms-4">
        <a class="p-1 btn btn-outline-primary"  href="{% url 'blog:list' %}" style="border: 1px solid lightgray; color: white;">Главная</a>
        <a class="p-1 btn btn-outline-primary" href="{% url 'blog:create' %}" style="border: 1px solid lightgray; color: white;">Создать блог</a>
    </nav>
</div>

{% block content %}
        {% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                OnlineShop
                <small class="d-block mb-3 text-muted">&copy; 2023 - {% now 'Y' %}</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'catalog:home' %}">Магазин</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'blog:list' %}">Наш блог</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

blog/templates/blog/blog_confirm_delete.html
{% extends 'blog/base_blog.html' %}

{% load my_tags %}

{% block content %}

<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row mb-3">
            <div class="row">
                <div class="col-sm-2"></div>
                <div class="col-sm-10">
                    <form method="POST">
                        {% csrf_token %}
                        <p>Хотите удалить блог "{{ object.title }}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'blog:list' %}" class="btn btn-success">Отменить</a>
                    </form>
                </div>
            </div>
            {% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'blog/base_blog.html' %}

{% load my_tags %}

{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        Просмотры: {{ object.views_count }}
        <div class="row">
            <div class="col-md-12 text-center">
               <h3 class="mb-5">{{ object.title }} - ({{ object.slug }})</h3>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <p class="mb-3" style="font-weight: normal; text-align: justify;">
                    <span style="text-indent: 1.25cm;">{{ object.content|linebreaksbr }}</span>
                </p>
            </div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'blog/base_blog.html' %}

{% load my_tags %}

{% block content %}

<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row mb-3">
            <div class="row">
                <div class="col-sm-2"></div>
                <div class="col-sm-10">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary btn-dark">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
            {% endblock %}

blog/templates/blog/blog_list.html
{% extends 'blog/base_blog.html' %}

{% load my_tags %}

{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-md-2 g-4">
            {% for object in object_list %}
            <div class="col mb-4">
                <div class="card h-100">
                    <div class="row g-0">
                        <div class="col-md-6">
                            <div class="card-body position-relative" style="max-width: 400px; max-height: 200px;">
                                <div class="position-absolute top-0">
                                    <div class="mb-1 text-body-secondary">
                                        <div class="text-end">{{ object.date_of_creation }}</div>
                                    </div>
                                </div>
                                <hr>
                                <h5 class="mb-2">{{ object.title|truncatechars:40 }}</h5>
                                <hr>
                                <p class="card-text mb-3">{{ object.content|truncatechars:55 }}</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a href="{% url 'blog:view' object.pk %}">
                                            <button class="btn btn-sm btn-secondary me-2">Просмотреть</button>
                                        </a>
                                        <a href="{% url 'blog:edit' object.pk %}">
                                            <button class="btn btn-sm btn-secondary me-2">Изменить</button>
                                        </a>
                                        <a href="{% url 'blog:delete' object.pk %}">
                                            <button class="btn btn-sm btn-secondary">Удалить</button>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 d-flex justify-content-end">
                            <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
                                <title>Placeholder</title>
                                <rect width="100%" height="100%" fill="#55595c"/>
                                <text x="50%" y="50%" text-anchor="middle" fill="#ffffff" font-size="20px">Просмотры: {{ object.views_count }}</text>
                            </svg><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
  {% endblock %}