blog/urls.py
from django.urls import path

from blog.apps import BlogConfig

from blog.views import BlogCreate, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreate.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, VerifyEmailView, CustomPasswordResetView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('verify_email/<str:uid>/<str:token>/', VerifyEmailView.as_view(), name='verify_email'),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.contrib.auth.models import User

from catalog.models import NULLABLE

class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    is_verified = models.BooleanField(default=False,verbose_name='подтвержден ли аккаунт')
    verification_token = models.CharField(max_length=100, blank=True)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    phone_number = models.CharField(max_length=35, verbose_name ='телефон', **NULLABLE)
    country = models.CharField(max_length=100, **NULLABLE)



    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from catalog.forms import StyleFormMixin
from users.models import User

class UserRegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(StyleFormMixin, UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'first_name', 'first_name', 'phone_number', 'country', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from random import random, randint

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordResetView
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.http import HttpResponseForbidden
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils.crypto import get_random_string
from django.views import View
from django.views.generic import CreateView, UpdateView


from users.forms import UserRegisterForm, UserProfileForm
from users.models import User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')


    def form_valid(self, form):
        response = super().form_valid(form)
        new_user = form.save()
        # Создаем и сохраняем токен подтверждения
        token = get_random_string(length=50)
        new_user.verification_token = token
        new_user.save()
        # Отправляем письмо с подтверждением
        current_site = get_current_site(self.request)
        mail_subject = 'Подтвердите ваш аккаунт'
        message = (
            f'Поздравляем, Вы зарегистрировались на нашем портале!\n'
            f'Для завершения регистрации и подтверждения вашей электронной почты, '
            f'пожалуйста, кликните по следующей ссылке:\n'
            f'http://{current_site.domain}{reverse("users:verify_email", kwargs={"uid": new_user.pk, "token": token})}'
        )
        send_mail(
            subject=mail_subject,
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[new_user.email]
        )
        return response


class VerifyEmailView(View):
    def get(self, request, uid, token):
        try:
            user = get_object_or_404(User, pk=uid, verification_token=token)
            user.is_verified = True
            user.save()
            return render(request, 'users/registration_success.html')  # Покажем сообщение о регистрации
        except User.DoesNotExist:
            return render(request, 'users/registration_failed.html')  # Покажем сообщение об ошибке

class ProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('catalog:home')

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_verified:
            return HttpResponseForbidden("Ваша электронная почта еще не проверена.")
        return super().dispatch(request, *args, **kwargs)


class CustomPasswordResetView(PasswordResetView):
    def form_valid(self, form):
        # Генерация нового случайного пароля
        new_password = ''.join([str(randint(0, 9)) for _ in range(12)])
        email = form.cleaned_data['email']
        User = get_user_model()
        user = User.objects.get(email=email)
        user.set_password(new_password)
        user.save()

        # Отправка нового пароля пользователю по электронной почте
        send_mail(
            subject='Восстановление пароля',
            message=f'Ваш новый пароль: {new_password}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email]
        )

        return super().form_valid(form)

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% load my_tags %}

{% block content %}

<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-6">
                <form method="POST" enctype="multipart/form-data" class="border p-4">
                    <h2 class="card-title">
                        Вход
                    </h2>
                    <div class="row mb-3">
                        <div class="col-sm-2"></div>
                        <hr>
                        <div class="col-sm-10">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">Войти</button>
                            <p>Забыли пароль? <a href="{% url 'users:password_reset' %}">Восстановить пароль</a></p>
                        </div>
                    </div>
                </div>
            </form>
            {% endblock %}

users/templates/users/password_reset.html
{% extends 'catalog/base.html' %}

{% load my_tags %}

{% block content %}
  <h1>Восстановление пароля</h1>
  <form method="POST" action="{% url 'users:password_reset' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Отправить</button>
  </form>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% load my_tags %}

{% block content %}

<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-6">
                <form method="POST" enctype="multipart/form-data" class="border p-4">
                    <h2 class="card-title">
                        Регистрация
                    </h2>
                    <div class="row mb-3">
                        <div class="col-sm-2"></div>
                        <hr>
                        <div class="col-sm-10">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">Регистрация</button>
                        </div>
                    </div>
                </div>
            </form>
            {% endblock %}

users/templates/users/registration_failed.html
<h1>Ошибка!</h1>
<p>Неверная ссылка подтверждения.</p>

users/templates/users/registration_success.html
<h1>Поздравляем!</h1>
<p>Вы успешно зарегистрировались на нашем портале.</p>
<a href="{% url 'users:login' %}">Войти</a>

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}

{% load my_tags %}

{% block content %}

<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-6">
                <form method="POST" enctype="multipart/form-data" class="border p-4">
                    <h2 class="card-title">
                        Профиль
                    </h2>
                    <div class="row mb-3">
                        <div class="col-sm-2"></div>
                        <hr>
                        <div class="col-sm-10">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">Сохранить</button>
                        </div>
                    </div>
                </div>
            </form>
            {% endblock %}