blog/urls.py
from django.urls import path

from blog.apps import BlogConfig

from blog.views import BlogCreate, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreate.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.views import contacts_page, ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, categories

from catalog.apps import CatalogConfig

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('contacts/', contacts_page, name='contacts'),
    path('product/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('create/', ProductCreateView.as_view(), name='create_product'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),
    path('categories/', categories, name='categories'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.contrib.auth import get_user_model


NULLABLE = {'blank': True, 'null': True}
class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование продукта')
    description = models.TextField(verbose_name='описание')
    preview = models.ImageField(upload_to='product/', verbose_name='изображение', **NULLABLE)
    category = models.ForeignKey('Category', on_delete=models.PROTECT)
    price = models.PositiveIntegerField(verbose_name='цена за штуку')
    date_of_creation = models.DateField(auto_now_add=True, verbose_name='дата создания')
    date_modification = models.DateField(auto_now=True, verbose_name='дата последнего изменения')
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, default=None, null=True, verbose_name='пользователь')
    is_published = models.BooleanField(default=False, verbose_name='статус публикации')

    class Meta:
        permissions = [
            ('set_published', 'Can publish posts'),
            ('change_product_description', 'Can change product description'),
            ('change_product_category', 'Can change product category'),
        ]

        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ('name',)

    def has_permission_to_change(self, user):
        return self.user == user

    def has_permission_to_delete(self, user):
        return self.user == user

    def __str__(self):
        return f'{self.name}'

    def get_active_version(self):
        try:
            return self.version_set.get(is_active=True)
        except Version.DoesNotExist:
            return None



class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование категории')
    description = models.TextField(verbose_name='описание')

    def __str__(self):
        return f'{self.name} {self.description}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    version_number = models.IntegerField(**NULLABLE, verbose_name='Номер версии')
    version_name = models.CharField(max_length=100, verbose_name='Наименование версии')
    is_active = models.BooleanField(default=True, verbose_name='Текущая версия')

    def __str__(self):
        return f"Версия {self.version_number} - {self.version_name} для продукта {self.product}"

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Version


forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin,forms.ModelForm):

    class Meta:
        model = Product
        fields = ('name', 'description', 'preview', 'category', 'price',)
        #fields = ('name', 'description' ) определенные атрибуты
        #exclude = ('preview') для исключения какого-либо атрибута


    def clean_name(self):
        name = self.cleaned_data.get('name', '')

        for word in forbidden_words:
            if word.lower() in name.lower():
                raise forms.ValidationError(f"Использование слова '{word}' запрещено в названии продукта.")

        return name

    def clean_description(self):
        description = self.cleaned_data.get('description', '')

        for word in forbidden_words:
            if word.lower() in description.lower():
                raise forms.ValidationError(f"Использование слова '{word}' запрещено в описании продукта.")

        return description


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.forms import inlineformset_factory
from django.template.context_processors import request
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Version
from  catalog.services import get_cached_categories
class ProductListView(ListView):
    model = Product
    template_name = 'catalog/home.html'
    context_object_name = 'products'


def contacts_page(request):
    return render(request, 'catalog/contacts.html')


class ProductDetailView(DetailView):
    model = Product
    template_name = 'catalog/product.html'


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'catalog/product_form.html'
    success_url = reverse_lazy('catalog:home')
    login_url = reverse_lazy('users:login')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    permission_required = 'catalog.change_product'
    success_url = reverse_lazy('catalog:home')
    formset_class = inlineformset_factory(Product, Version, form=VersionForm, extra=1, fields=('version_number',
                                                                                               'version_name',
                                                                                               'is_active'))

    def has_permission(self):
        product = self.get_object()
        return product.has_permission_to_change(self.request.user)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if self.request.method == 'POST':
            context_data['formset'] = self.formset_class(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = self.formset_class(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Product
    permission_required = 'catalog.delete_product'
    success_url = reverse_lazy('catalog:home')

    def has_permission(self):
        product = self.get_object()
        return product.has_permission_to_delete(self.request.user)

def categories(request):
    context = {
        'object_list': get_cached_categories(),
        'title': 'Все категории'
    }
    return render(request, 'catalog/categories.html', context)

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>OnlineShop</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    {% block css %}
    {% endblock %}
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">OnlineShop</h5>
    {% include 'catalog/includes/inc_main_menu.html' %}
</div>

{% block content %}
        {% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                OnlineShop
                <small class="d-block mb-3 text-muted">&copy; 2023 - {% now 'Y' %}</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'catalog:home' %}">Магазин</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'blog:list' %}">Наш блог</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/categories.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-5">Все категории</h1>
</div>
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row mb-3">
            <div class="row">
                <div class="col-sm-2"></div>
                <div class="col-sm-10">
                    {% for category in object_list %}
                    <li>{{ category.name }}</li>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row text-start">
            <div class="col-lg-9 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <table class="table table-striped">
                            <tr>
                                <td class="w-25">Страна</td>
                                <td>USA</td>
                            </tr>
                            <tr>
                                <td class="w-25">ИНН</td>
                                <td>91-1144442</td>
                            </tr>
                            <tr>
                                <td class="w-25">Адрес</td>
                                <td>Redmond,WA,98052-6399</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" action="" class="form-floating">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name">Ваше имя</label>
                                <br>
                                <input type="text" name="name" class="form-control" id="name" placeholder="Введите имя" required>
                            </div>
                            <div class="mb-3">
                                <label for="phone">Телефон</label>
                                <br>
                                <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                            </div>
                            <div class="mb-3">
                                <label for="message">Сообщение</label>
                                <br>
                                <textarea type="text" name="message" class="form-control" id="message" placeholder="Сообщение" required></textarea>
                            </div>
                        </form>
                        <br>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block css %}
<style>
    .card {
        width: 300px;
        height: 400px;
    }
</style>
{% endblock %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">OnlineShop</h1>
    <p class="lead">OnlineShop – это виртуальный мир, где каждый может найти то, что ему по душе. Здесь вы найдете товары на любой вкус и кошелек, а также получите отличный сервис и быструю доставку. Мы заботимся о наших клиентах и стремимся сделать их жизнь проще и удобнее</p>
</div>

<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            <div class="col col-sm-6">
                <div class="card shadow-sm">
                    <img src="{{ object.preview.url }}" class="bd-placeholder-img card-img-top" width="100%" height="225" alt="Product Image">
                    <div class="card-body">
                        <p class="card-text">{{ object.name|truncatechars:30 }}</p>
                        {% if active_versions %}
                            {% for version in active_versions %}
                                {% if version.product == object %}
                                    <p>Active Version: {{ version.version_name }}</p>
                                    <!-- Другие поля активной версии, которые вы хотите отобразить -->
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'catalog:product_detail' object.pk %}" class="btn btn-sm btn-outline-secondary">Посмотреть</a>
                                {% if user.is_authenticated %}
                                    {% if object.user == request.user or perms.catalog.change_product %}
                                        <a href="{% url 'catalog:update_product' object.pk %}" class="btn btn-sm btn-outline-secondary">Редактировать</a>
                                    {% endif %}
                                    {% if object.user == request.user or perms.catalog.delete_product %}
                                        <a href="{% url 'catalog:delete_product' object.pk %}" class="btn btn-sm btn-outline-secondary">Удалить</a>
                                    {% endif %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
{% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block css %}
<style>
    .card-img-top {
        width: 15cm;
        height: 20cm;
        object-fit: contain;
    }

    .product-image {
        display: flex;
        justify-content: center;
        align-items: center;
    }
</style>
{% endblock %}

{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <h1 align="center">{{ product.name }}</h1>
        <div class="product-image">
            <img src="{{ product.preview|mediapath }}" class="bd-placeholder-img card-img-top" alt="Product Image">
        </div>
        <p><strong>Цена: {{ product.price }}</strong></p>
        <p align="justify">Описание: {{ product.description }}</p>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% load my_tags %}

{% block content %}

<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row mb-3">
            <div class="row">
                <div class="col-sm-2"></div>
                <div class="col-sm-10">
                    <form method="POST">
                        {% csrf_token %}
                        <p>Хотите удалить "{{ object.name }}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'catalog:home' %}" class="btn btn-success">Отменить</a>
                    </form>
                </div>
            </div>
            {% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% load my_tags %}

{% block content %}

<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <form method="POST" enctype="multipart/form-data">
        <h2 class="card-title">
            {% if object %}
                Редактирование продукта
            {% else %}
                Добавление продукта
            {% endif %}
        </h2>
        <div class="row mb-3">
            <div class="col-sm-2"></div>
            <hr>
            <div class="col-sm-10">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                            Сохранить
                        {% else %}
                            Создать
                        {% endif %}
                    </button>
                </div>
        </div>
            <h2 class="card-title">
                {% if object %}
                Редактирование версии
                {% else %}
                Добавление версии
                {% endif %}
            </h2>
            <div class="row mb-3">
                <div class="col-sm-2"></div>
                <hr>
                <div class="col-sm-10">
                    {{ formset.managment_form }}
                    {% for form in formset.forms %}
                        {{ form.as_table }}
                        {% if not forloop.last %}
                            <hr>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </form>
        {% endblock %}